### ISSUE TITLE
Accuracy on RAVEN-FAIR dataset is higher(98%) than that in the paper(88%)

### ISSUE THREAD

**Issue by WuGuommming** [yanivbenny/MRNet#1]
I downloaded the pre training model you provided on Google disk and generated raven-fair dataset according to the project on GitHub
![image](https://user-images.githubusercontent.com/35882620/147730599-08f9bd68-e1d3-4628-b2bb-d52286f90fb6.png)

The accuracy of the first epoch trained from the breakpoint has been significantly improved
![image](https://user-images.githubusercontent.com/35882620/147730622-b5af0b31-ab6d-4bf8-91b3-9c8842623422.png)

The accuracy of the follow-up results is much higher than that in the paper.
![image](https://user-images.githubusercontent.com/35882620/147730657-956b277e-1220-40de-9028-4ef6e6e2ae48.png)

The performence of training from scratch on RAVEN-FAIR is similar.

The results of the original Raven dataset training from scratch are consistent with the paper, but raven-fair is directly generated by GitHub, and there should be no problem, so I can't judge where there is a problem.

Therefore, I would like to consult you. Thank you

**Comment by WuGuommming** [comment]
I seem to have found the problem: the npz file of the original RAVEN dataset is much bigger raven-fair
![d60ba927ca5d63f34a6fb70d948ab65](https://user-images.githubusercontent.com/35882620/147802823-e0896150-3618-46af-91ca-0530e33ee371.png)

![74e34194669fa1dbbf69ea2ee08813b](https://user-images.githubusercontent.com/35882620/147802826-1034facb-daaf-4cca-a383-60ae1eaa1e0f.png)


But I don't know why and how to solve this problem.

This is my environment for RAVEN_ FAIR-master.
![image](https://user-images.githubusercontent.com/35882620/147802978-b9b4515c-3871-4b12-941b-41358b29eb5f.png)


This is the command I used to generate the raven-fair dataset.
`python main.py --fair 1 --save-dir ../../dataset/`

**Comment by yanivbenny** [comment]
Hi

Let me look at it and get back to you

‫בתאריך יום ו׳, 31 בדצמ׳ 2021 ב-6:18 מאת ‪WuGuommming‬‏ <‪
***@***.***‬‏>:‬

**Comment by yanivbenny** [comment]
Sorry for this very late response.

There was a bug that resulted in all raven splits to take all train+val+test samples.
This resulted in higher accuracy since it was computed on the train samples as well.

This issue has been resolved.
